<a href="https://colab.research.google.com/github/chryssleirodriguez/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
## Assignment 3: Matrices

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.


# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

# Matrices

In [ ]:
$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-2x+3y-4z \\
        3w- x -2y +z \\
        2w -x + 3y - 2z
    \end{array}
\right. $$

SyntaxError: ignored

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -3 & 2 & -4 \\ 3 & -4 & -2 & 1 \\ 3 & -2 & -5 & -3\end{bmatrix}
$$


$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [11]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [12]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)


Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [17]:
G = np.array([
    [2,5,4],
    [4,9,6]
])
describe_mat(G)


Matrix:
[[2 5 4]
 [4 9 6]]

Shape:	(2, 3)
Rank:	2



In [18]:
## Declaring a 3 x 2 matrix\
B = np.array([
    [7, 3],
    [4, 1],
    [9, 3]
])
describe_mat(B)


Matrix:
[[7 3]
 [4 1]
 [9 3]]

Shape:	(3, 2)
Rank:	2



In [19]:
H = np.array([4,3,2,1])
describe_mat(H)


Matrix:
[4 3 2 1]

Shape:	(4,)
Rank:	1



In [21]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    5, 4, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [3,1,2, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[5 4 3 2]

Shape:	(4,)
Rank:	1

Matrix:
[[ 3  1  2 -4]]

Shape:	(1, 4)
Rank:	2



In [23]:
## Declaring a Column Matrix

col_mat = np.array([
    [5],
    [3],
    [1]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[5]
 [3]
 [1]]

Shape:	(3, 1)
Rank:	2



In [24]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [25]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



In [26]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [30]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


In [31]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [32]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [33]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])


array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [34]:
d = np.diag([2,3,5,7])
#d.shape[0] == d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.identity(20)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [39]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])


array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [40]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)


array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

In [41]:
np.tril(F)


array([[ 2,  0,  0,  0,  0],
       [ 2, -3,  0,  0,  0],
       [ 2, -3,  4,  0,  0],
       [ 2, -3,  4, -5,  0],
       [ 2, -3,  4, -5,  6]])

Given the linear combination below, try to create a corresponding matrix representing it.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [42]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [43]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])