<a href="https://colab.research.google.com/github/chryssleirodriguez/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Rodriguez_Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 6 : Matrix Operations
Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

##Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

##Transposition

Transposition is a fundamental operation in matrix algebra. The transpose of a matrix is found by reversing its rows into columns or columns into rows. The matrix's transpose is denoted by the letter "T" in the superscript of the provided matrix. For example, if "A" is the given matrix, the matrix's transpose is denoted as A' or AT. So for example:



$$A = \begin{bmatrix} 4 & 1 & 6\\3 & -4 &9 \\ -5 & 6 & 8\end{bmatrix} $$

$$A^T = \begin{bmatrix} 4 & 3 & -5\\1 & -4 &6 \\ 6 & 9 & 8\end{bmatrix} $$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [2]:
A = np.array([
    [4, 1, 6],
    [3, -4, 9],
    [-5, 6, 8]
])
A

array([[ 4,  1,  6],
       [ 3, -4,  9],
       [-5,  6,  8]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[ 4,  3, -5],
       [ 1, -4,  6],
       [ 6,  9,  8]])

In [4]:
AT2 = A.T
AT2

array([[ 4,  3, -5],
       [ 1, -4,  6],
       [ 6,  9,  8]])

In [5]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array([
    [2,4,6,8],
    [1,3,5,7]
])
B.shape

(2, 4)

In [8]:
np.transpose(B).shape

(4, 2)

In [9]:
B.T.shape

(4, 2)

#### Try to create your own matrix (you can try non-squares) to test transposition.

In [10]:
## Try out your code here.
Z=np.array([
    [5,4,3,2],
    [1,2,3,4],
    [0,9,8,7]        
])
Z.shape

(3, 4)

In [11]:
np.transpose(Z).shape

(4, 3)

In [12]:
Z.T.shape

(4, 3)

In [13]:
ZT = Z.T012
ZT

array([[5, 1, 0],
       [4, 2, 9],
       [3, 3, 8],
       [2, 4, 7]])

##Dot Product/Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

In [14]:
O = np.array([
    [2,5,4],
    [3,1,-5],
    [4,9,0]
])
P = np.array([
    [2,-3,1],
    [9,0,7],
    [1,1,2]
])

In [15]:
np.array_equiv(O, P)

False

In [16]:
np.dot(O, P)

array([[ 53,  -2,  45],
       [ 10, -14,   0],
       [ 89, -12,  67]])

In [17]:
O.dot(P)

array([[ 53,  -2,  45],
       [ 10, -14,   0],
       [ 89, -12,  67]])

In [18]:
O@P

array([[ 53,  -2,  45],
       [ 10, -14,   0],
       [ 89, -12,  67]])

In [19]:
np.matmul(O,P)

array([[ 53,  -2,  45],
       [ 10, -14,   0],
       [ 89, -12,  67]])

In [20]:
C = np.array([
    [7,1,1],
    [6,2,1],
    [0,1,4]
])
D = np.array([
    [2,1,0],
    [6,2,-1],
    [0,9,4],
])
print(C.shape)
print(D.shape)

(3, 3)
(3, 3)


In [21]:
C@D

array([[20, 18,  3],
       [24, 19,  2],
       [ 6, 38, 15]])

In [22]:
C.dot(D)

array([[20, 18,  3],
       [24, 19,  2],
       [ 6, 38, 15]])

In [23]:
np.matmul(C, D)

array([[20, 18,  3],
       [24, 19,  2],
       [ 6, 38, 15]])

In [24]:
np.dot(C, D)

array([[20, 18,  3],
       [24, 19,  2],
       [ 6, 38, 15]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [25]:
E = np.array([
    [1, 0, 2, 4],
    [-9, 3, 8, -3],
    [4, -7, 5, 0]
])
F = np.array([
    [6, 1, 0, -2],
    [4, -2, 2, 0],
    [-4, 0, 3, 8]
])
G = np.array([
    [2, 4],
    [1, 3],
    [0, 9],
    [7, -3]
])
print(E.shape)
print(F.shape)
print(G.shape)

(3, 4)
(3, 4)
(4, 2)


In [26]:
E@G

array([[ 30,  10],
       [-36,  54],
       [  1,  40]])

In [27]:
F@G

array([[ -1,  33],
       [  6,  28],
       [ 48, -13]])

In [28]:
## Error because it does not follow the rule 1
E@F

ValueError: ignored

And youcan see that when you try to multiply E and F, it returns `ValueError` pertaining to matrix shape mismatch.

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix  E  with a shape of  (a,b)  and matrix  F  with a shape of  (b,c) ,  E⋅F  should have a shape  (a,c) .



In [29]:
E@F.T

array([[ -2,   8,  34],
       [-45, -26,  36],
       [ 17,  40,  -1]])

In [30]:
H = np.array([
    [-1,9,1,7]
])
I = np.array([
    [5,-3,2,-1]
])
print(H.shape)
print(I.shape)

(1, 4)
(1, 4)


In [31]:
I.T@H

array([[ -5,  45,   5,  35],
       [  3, -27,  -3, -21],
       [ -2,  18,   2,  14],
       [  1,  -9,  -1,  -7]])

In [32]:
H@I.T

array([[-37]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [33]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,1]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
A.dot(np.eye(3))

array([[3., 2., 1.],
       [4., 5., 1.],
       [1., 1., 1.]])

In [36]:
## A.B ≠ B.A
np.array_equal(A@B, B@A)

False

In [37]:
## A@(B@C)=(A@B)@C
X = A @ (B @ C)
X

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [38]:
Y = (A @ B) @ C
Y

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [39]:
np.array_equal(X, H)

False

In [40]:
np.array_equal(X, Y)

True

In [41]:
A@X

array([[455, 205, 368],
       [862, 385, 691],
       [211,  95, 172]])

In [42]:
## A@(B+C)=(A@B)+(A@C)
V = (A@B)+(A@C)
V

array([[25, 14, 47],
       [42, 22, 83],
       [11,  8, 25]])

In [43]:
W = A@(B+C)
W

array([[25, 14, 47],
       [42, 22, 83],
       [11,  8, 25]])

In [44]:
np.array_equal(V, W)

True

In [45]:
## (B+C)@A=(B@A)+(C@A)
J = (B+C)@A
J

array([[29, 26, 13],
       [30, 28, 16],
       [31, 33, 15]])

In [46]:
K = (B@A)+(C@A)
K

array([[29, 26, 13],
       [30, 28, 16],
       [31, 33, 15]])

In [47]:
np.array_equal(J, K)

True

In [48]:
##A@I=A
L = np.identity(3)
L

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
S = A@L
S

array([[3., 2., 1.],
       [4., 5., 1.],
       [1., 1., 1.]])

In [50]:
np.array_equal(A, S)

True

In [51]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.array_equal(a_dot_z,z_mat)

True

In [54]:
## A.∅=∅
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

In [55]:
R = A@a_dot_z
R

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.array_equal(R, a_dot_z)

True

##Determinant
The determinant of a matrix is a number that is exclusively specified for square matrices. Determinants are mathematical objects that can be used to analyze and solve systems of linear equations. Determinants have numerous uses in engineering, science, economics, and social science.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [57]:
E = np.array([
    [9,8],
    [1,4]
])
np.linalg.det(E)

28.00000000000001

In [58]:
F = np.array([
    [-2,3,6],
    [0,1,4],
    [1,9,4]
])
np.linalg.det(F)

70.00000000000003

##Inverse
The inverse of a matrix A is denoted by A-1. A simple formula can be used to calculate the inverse of a 2x2 matrix. Furthermore, in order to obtain the inverse of a 3x3 matrix, we must first determine the determinant and adjoint of the matrix. The inverse of a matrix is another matrix that yields the multiplicative identity when multiplied with the supplied matrix.
The inverse of a matrix is used to solve linear equations using the matrix inversion method.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [59]:
M = np.array([
    [2,4],
    [6,-8]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [60]:
P = np.array([
              [5,6,7],
              [1,-2,0],
              [9,-6,2]
])
Q = np.linalg.inv(P)
Q

array([[-0.07692308, -1.03846154,  0.26923077],
       [-0.03846154, -1.01923077,  0.13461538],
       [ 0.23076923,  1.61538462, -0.30769231]])

In [61]:
P@Q

array([[1.00000000e+00, 0.00000000e+00, 1.66533454e-16],
       [1.38777878e-17, 1.00000000e+00, 5.55111512e-17],
       [1.11022302e-16, 4.44089210e-16, 1.00000000e+00]])

In [62]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [63]:
squad = np.array([
    [1.3, 1.0, 1.5],
    [0.7, 1.7, 0.9],
    [1.3, 0.3, 0.5]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[1.36],
       [1.02],
       [0.62]])

In [64]:
G = np.array([
    [0,2,1],
    [-5,8,3],
    [3,1,7]
])
H = np.linalg.inv(G)
H

array([[ 0.89830508, -0.22033898, -0.03389831],
       [ 0.74576271, -0.05084746, -0.08474576],
       [-0.49152542,  0.10169492,  0.16949153]])

In [65]:
G@H

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [ 4.44089210e-16,  1.00000000e+00,  0.00000000e+00],
       [-4.44089210e-16,  4.16333634e-17,  1.00000000e+00]])

# Activity

###Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [66]:
A = np.array([
    [8,1,2],
    [9,4,3],
    [3,4,1]
])
B = np.array([
    [2,4,5],
    [5,1,6],
    [6,9,3]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [67]:
## A@B ≠ B@A
D = A@B
D

array([[33, 51, 52],
       [56, 67, 78],
       [32, 25, 42]])

In [68]:
E = B@A
E

array([[ 67,  38,  21],
       [ 67,  33,  19],
       [138,  54,  42]])

In [69]:
np.array_equal(D@E, E@D)

False

In [70]:
## A@(B@C)=(A@B)@C
F = A @ (B @ C)
F

array([[ 85,  84, 103],
       [134, 123, 145],
       [ 74,  57,  67]])

In [71]:
G = (A @ B) @ C
G

array([[ 85,  84, 103],
       [134, 123, 145],
       [ 74,  57,  67]])

In [72]:
np.array_equal(F, G)

True

In [73]:
## A@(B+C)=(A@B)+(A@C)
H = (A@B)+(A@C)
H

array([[43, 60, 55],
       [68, 80, 85],
       [36, 32, 47]])

In [74]:
I = A@(B+C)
I

array([[43, 60, 55],
       [68, 80, 85],
       [36, 32, 47]])

In [75]:
np.array_equal(H, I)

True

In [76]:
## (B+C)@A=(B@A)+(C@A)
J = (B+C)@A
J

array([[ 84,  43,  26],
       [ 79,  41,  23],
       [149,  59,  45]])

In [77]:
K = (B@A)+(C@A)
K

array([[ 84,  43,  26],
       [ 79,  41,  23],
       [149,  59,  45]])

In [78]:
np.array_equal(J, K)

True

In [79]:
##A@I=A
L = np.identity(3)
L

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
M = A@L
M

array([[8., 1., 2.],
       [9., 4., 3.],
       [3., 4., 1.]])

In [81]:
np.array_equal(A, M)

True

In [82]:
## A.∅=∅
N = A.dot(np.zeros(A.shape))
N

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(N,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

In [84]:
O = A@N
O


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.array_equal(N, O)

True

##References

1.   https://byjus.com/maths/transpose-of-a-matrix/
2.   https://www.toppr.com/guides/maths/determinants/determinant-of-a-matrix/
3.   https://www.cuemath.com/algebra/inverse-of-a-matrix/

